### ISSUE TITLE
Link generated is not getting the right protocol

### ISSUE THREAD

**Issue by beowshawitz** [SoapBox/jQuery-linkify#20]
I have tested this on a few situations, where I open a modal and dump text into a span tag Then I execute linkify against the span tag. I have something like...
https://www.google.com
ftp://www.google.com

inside the span tag. When I linkify the span tag, I am always getting http://www.google.com. It seems like line 45 is always applying http?

Any help would be appreciated.

**Comment by nfrasser** [comment]
Fixed in #51
