### ISSUE TITLE
Unlinkify Enhancement Request

### ISSUE THREAD

**Issue by pauliew** [SoapBox/jQuery-linkify#25]
The ability to redact links would be a useful addition where you can pass a string of what a url should be redacted to.

e.g.:
    if(linksAllowed){
        $Item.linkify();
    }
    else{
        $Item.linkify('unlink', '[link removed]');
    }

**Comment by nfrasser** [comment]
This is now available via the `format` option. [Example here](https://github.com/SoapBox/jQuery-linkify/issues/16#issuecomment-112130329).
