### ISSUE TITLE
ftp or any links other than http as a protocol

### ISSUE THREAD

**Issue by shrimalmadhur** [SoapBox/jQuery-linkify#27]
I am using linkify on ftp://abc.com (suppose). The linkified value has href as http://abc.com rather then ftp://abc.com
I see that you are hard coding http:// while making link replace. The only reason I could find out of this is when someone type google.com then it should come out as http://google.com but then it is creating issue with other protocols.

      linkReplace.push(
		'$1<' + settings.tagName,
		'href="http://$2$4$5$6$7"'
	);

**Comment by nfrasser** [comment]
Fixed in #51
