### ISSUE TITLE
Capital letters in domain names

### ISSUE THREAD

**Issue by shrimalmadhur** [SoapBox/jQuery-linkify#30]
If I use capital letters in domain names, it is not getting linkified. For example www.Google.com 
Is there any reason for the same?

**Comment by ranaesam** [comment]
i updated the regular expression by adding A-Z in different line that we have a small letter a-z and it's working now , Are these changes not destroy the linkify functions .

**Comment by Payetus** [comment]
@ranaesam  Can you post the changes you made in the source Code?

**Comment by gvinter** [comment]
+1

**Comment by Payetus** [comment]
Hey guys although ranaesam didnt post the code ¬¬. I figured out how to do it : 
Changing        join(""), "g"),   --------------> join(""), "gi"),  fixes the problem

**Comment by ranaesam** [comment]
Hi
i added [A-Z]  in the regular expression in the file , please find that in the picture below
![linkify](https://cloud.githubusercontent.com/assets/8872183/6798033/e17d18be-d211-11e4-9fe4-5f302d304566.png)

**Comment by Payetus** [comment]
Thanks @ranaesam

**Comment by nfrasser** [comment]
Fixed in #51
