### ISSUE TITLE
Links with @ in it.

### ISSUE THREAD

**Issue by shrimalmadhur** [SoapBox/jQuery-linkify#33]
So, I have have link with "@" in it. It doesn't get linkified. https://www.abc.com//login/confirm/?email=abc@gmail.com
Any particular reason for this behavior because I can see a very small fix in the Regex, where we add "@" at two places (7. Query String).

Also
for Google Maps also we have "@" in links
https://www.google.com/maps/dir/Begumpet,+Hyderabad,+Andhra+Pradesh,+India/Hitech+City,+Hyderabad,+Andhra+Pradesh,+India/@17.4376827,78.3875553,13z/data=!3m1!4b1!4m13!4m12!1m5!1m1!1s0x3bcb90a3ed28854f:0x20084b938c2f1b8c!2m2!1d78.4663812!2d17.4447068!1m5!1m1!1s0x3bcb93dc8c5d69df:0x19688beb557fa0ee!2m2!1d78.3773954!2d17.445824

**Comment by nfrasser** [comment]
Fixed in #51
