### ISSUE TITLE
Why all 2-Letter TLDs are Valid?

### ISSUE THREAD

**Issue by derektom14** [SoapBox/jQuery-linkify#38]
I was getting some complaints using linkify that many things that clearly weren't links (like referencing files with short extensions) were being linkified. Investigating, I found that the regex included this for identifying top-level domains:
com|ca|co|edu|gov|net|org|dev|biz|cat|int|pro|tel|mil|aero|asia|coop|info|jobs|mobi|museum|name|post|travel|local|[a-z]{2}
Clearly the final [a-z]{2} is going to lead to many false positives, so why exactly is this part of the regex?

**Comment by nfrasser** [comment]
Fixed in #51
