### ISSUE TITLE
Need a callback once linkify finishes

### ISSUE THREAD

**Issue by mswanson** [SoapBox/jQuery-linkify#43]
First, thanks for the great work on this plugin. The way we currently have it implemented I need to do some post processing after Linkify completes. I have read the docs and looked at the source and I was wondering why you have not implemented any callbacks or a way to pass one in as an option. I am happy to extend the plugin to do so I was just curious if this request has been made before.

Thanks

**Comment by nfrasser** [comment]
Fixed in #51 with the `format` option. [Example here](https://github.com/SoapBox/jQuery-linkify/issues/16#issuecomment-112130329).

`formatHref` works similarly, except you can use it to format the `href` attribute of the URL (which may be different from the displayed URL.
