### ISSUE TITLE
[object NodeList] error when testing with phantomjs

### ISSUE THREAD

**Issue by benr77** [SoapBox/jQuery-linkify#46]
When running headless browser tests on my project using PhantomJS and CasperJS I get the following error on one of my pages. This error does not crop up on any normal browser so I can only assume it's related to PhantomJS itself.

```TypeError: '[object NodeList]' is not a valid argument for 'Function.prototype.apply' (evaluating 'g.childNodes')```

**Comment by nfrasser** [comment]
Fixed in #51

**Comment by drewbietron** [comment]
Updated to 2.0 to mend this issue but linkify.js is not included in the 2.0 beta bower package.   Only linkify.js is in the dist/ folder which prints a deprecation warning to console.

**Comment by nfrasser** [comment]
@drewbietron 2.0 is a complete rewrite from 1.1.7.  You should install with the command `bower install linkifyjs#v2.0.0-beta.5`. Then use `bower_components/linkifyjs/linkify.js` and `bower_components/linkifyjs/linkify-jquery.js`. Full setup docs are found [here](http://soapbox.github.io/linkifyjs/docs/).

`src/linkified.js` (which I'm guessing is the file you're referring to) is in 1.1.7 only and should not be used directly.
