### ISSUE TITLE
Separate funcionality from DOM element.

### ISSUE THREAD

**Issue by kafeltz** [SoapBox/jQuery-linkify#55]
I want to use Linkify object without attaching to an DOM element.

The plugin works great, but I want to use it with strings and do my stuffs and later I will create a DOM element with my template engine.

But the object constructor wants a dom element when the plugin is instanciated: new Linkfy( element, options).

Its just and idea.

**Comment by nfrasser** [comment]
Great suggestion @kafeltz ! Linkify 2.0 ( #51 ) will actually have a dedicated string-parsing function for exactly this purpose

**Comment by kafeltz** [comment]
Perfect!
