### ISSUE TITLE
Is jQuery necessary?

### ISSUE THREAD

**Issue by dandv** [SoapBox/jQuery-linkify#56]
Haven't kept up to date with the latest developments, but I've seen the Jan 1st PR with the Node.js API. Is jQuery still required on the client? Seems that URL parsing is a JavaScript problem, but it may be that the library does some additional processing.

**Comment by nfrasser** [comment]
As of 1.x, jQuery is still required. Once 2.0 is released, you'll be able to select one or more of 3 interfaces: 

1. **string** (to linkify Strings)
2. **element** (to linkify DOM nodes, including virtual DOMs like [jsdom](https://github.com/tmpvar/jsdom) in Node.js)
3. **jquery** (to linkify jQuery objects)

jQuery will be required *only* for the third one (you can import only the interfaces you need).

**Comment by nfrasser** [comment]
Of course the documentation will be updated to reflect the new changes, and a `jquery.linkify.js` file will be kept around for backward compatibility. We'll probably be changing the name of the repo as well

**Comment by nfrasser** [comment]
Fixed in #51
