### ISSUE TITLE
Allow jQuery 1.x

### ISSUE THREAD

**Issue by sloria** [SoapBox/jQuery-linkify#59]
Currently, this package depends on jQuery 2.x. It would be great if the 1.x line (which is still maintained) were also supported. The 1.x line has support for older browsers, and the 2.x is mostly backwards-compatible.

**Comment by nfrasser** [comment]
Could you please clarify? 1.x is specified in [bower.json](https://github.com/SoapBox/jQuery-linkify/blob/master/bower.json) and most of the documentation. I'm not sure where you're seeing 2.x

**Comment by sloria** [comment]
Ah, disregard. I was looking at the current distribution on NPM, which depends on jquery 2. Looks like this has been changed since the last release. Sorry for the noise.
