### ISSUE TITLE
What is the official way to install this plugin?

### ISSUE THREAD

**Issue by kminh** [SoapBox/jQuery-linkify#63]
Hi, thank you for this useful library.

I'm confused as to how I should install this plugin? Putting something like this in `package.json`?

```
    "linkifyjs": "^2.0.0-alpha.3"
```

If I use the above approach, the `dist` folder only has a single zip file. Shouldn't it be populated with minified source files, ready for use?

And since this plugin is named jquery-linkify, I also find it confusing when I have to include both `linkify.min.js` and `linkify.jquery.min.js`. 

Appreciate any insight.

**Comment by nfrasser** [comment]
v2.0.0 has not been officially released yet. Will update with installation instructions shortly.

**Comment by nfrasser** [comment]
`bower install linkifyjs` should now work as of `2.0.0-beta.1`.
