### ISSUE TITLE
Url followed by double quote can lock up/freeze browser

### ISSUE THREAD

**Issue by laubsauger** [SoapBox/jQuery-linkify#64]
Occurs only with specific path structure, e.g. path is segmented with dashes or underscores.

**Tested with linkify 1.1.6 + 1.1.7 @ Chrome 43 + Firefox 36**

A few benchmarked cases

`"visit https://www.example.com/", she said.`
d.linkifyNode => 1.0ms / 3.45%

`"visit https://www.example.com/path/to/doom/d_1", she said.`
d.linkifyNode => 3ms / 10.71%

`"visit https://www.example.com/path/to/doom/d_1_d_2", she said.`
d.linkifyNode => 39.3ms / 60%

`"visit https://www.example.com/path/to/doom/d_1_d_2_d_3", she said.`
d.linkifyNode => 643.2ms / 97.11%

`"visit https://www.example.com/path/to/doom/d_1_d_2_d_3_d_4", she said.`
d.linkifyNode => 9961.3ms / 99.73%

`https://www.example.com/path/to/doom/d_1_d_2_d_3_d_4"`
d.linkifyNode => 4837.4ms / 99.75%

Starting from here (10 segments and up) my browser tab just freezes up:
`https://www.example.com/path/to/doom/d_1_d_2_d_3_d_4_d_5"`
`https://www.example.com/path/to/doom/d-1-d-2-d-3-d-4-d-5"`
d.linkifyNode => n/a

No double quote, all is well:
`https://www.example.com/path/to/doom/d_1_d_2_d_3_d_4`
d.linkifyNode => 1ms / 99.75%

**FYI Issue seems to be resolved in 2.0.0-alpha (tested prerelease-3) but i wanted to report this anyway**

**Comment by nfrasser** [comment]
Fixed in #51. Thanks for reporting this.
