### ISSUE TITLE
Links not recognized and too long

### ISSUE THREAD

**Issue by simonferndriger** [SoapBox/jQuery-linkify#66]
![bug](https://cloud.githubusercontent.com/assets/1435963/7953761/cb019062-09c8-11e5-82ef-eb94acfb31b0.PNG)

**Problem 1)**
The link does not get recognized, I guess it is because it follows the "..." without a space (what should I say, it's not a nice way to place a link, but unfortunately it happens).

**Problem 2)**
The link is too long. Is there a way to have the option to cut links into a certain length?

**Comment by nfrasser** [comment]
Fixed in #51. Your link should now be recognized.

You can truncate URLs with the new `format` option. [Example here](https://github.com/SoapBox/jQuery-linkify/issues/16#issuecomment-112130329)

**Comment by simonferndriger** [comment]
But your code is now at least double as heavy! What happened to the lightweight plugin?...

**Comment by nfrasser** [comment]
There is definitely more code now, the reason being better efficiency, maintainability, and extensibility. However, we've done a ton of work to keep the code very compressible, so your load time should not be heavily impacted.

The compiled .min files have been moved to https://github.com/nfrasser/linkify-shim, or you can download them from Bower, or the Releases section of this repository.
